# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'driftproj' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for driftproj

  target 'driftproj-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'driftprojTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'driftproj-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for driftproj-tvOS

  target 'driftproj-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
